In [ ]:
import numpy as np
a=np.array([[]])
a.ndim
a.shape

(1, 0)

In [ ]:
a.shape

In [ ]:
#range=np.arrange(1,10,2)#start,stop,step value
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr=np.logspace(1,3,3)#logarithmic scale array (startpower value,end power value,number value how many times to be repeated)
arr

array([  10.,  100., 1000.])

In [ ]:
#array full of zeros
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros([2,3])#creates a matrix with zero as the value as (row,col)
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr=np.ones([2,2],dtype=int)#same as zeros only 1 is the value in the matrix
arr#dtype is by default float value not int

array([[1, 1],
       [1, 1]])

In [ ]:
arr=np.full(10,2)#array full of value of our choice(no.of values to be displayed,no.of times it must repeat)
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr=np.full([2,4],8)#([row,col],value)
arr

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [ ]:
arr=np.empty([2,3])#unintialized array(row,col)
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr=np.random.rand(10)#generate random float values
arr

array([0.90476074, 0.7789105 , 0.68980569, 0.47888339, 0.19778777,
       0.68711202, 0.26071585, 0.90015291, 0.73280076, 0.93340327])

In [ ]:
arr=np.random.rand(2,3)#(row,col)
arr

array([[0.14334247, 0.51998379, 0.50467993],
       [0.58021785, 0.91973414, 0.62744663]])

In [ ]:
arr=np.random.randn(2,3)#random floats from standard distribution
arr

array([[-0.38532327,  0.62600437,  0.76773937],
       [ 0.02256819,  1.6424764 ,  0.19139932]])

In [ ]:
arr=np.random.randint(10,99)#random numberfrom 10 to 99
arr

77

In [ ]:
arr=np.random.randint(10,99,size=(2,3))#random numberfrom 10 to 99 in 2 by 3 array
arr

array([[63, 78, 66],
       [15, 59, 63]])

In [ ]:
######Numpy Datatype and Type Casting########


In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

arr=np.array([1,2,3.1,4,5])#Numpy does not allow multiple datatypes in one array
arr

In [ ]:
lst=['string',1,1.2,'Hello123']
print(lst)#python list displays every datatype
arr=np.array(lst)
arr#Nump converts every datatype into string

['string', 1, 1.2, 'Hello123']


array(['string', '1', '1.2', 'Hello123'], dtype='<U32')

In [ ]:
arr=np.array([1,2,3,4,5])#Check the default datatype of numpy array
print(arr)
arr.dtype


[1 2 3 4 5]


dtype('int64')

In [ ]:
arr=np.array([1,2,1.3,4,5])#Check the default datatype of numpy array
print(arr)
arr.dtype


[1.  2.  1.3 4.  5. ]


dtype('float64')

[1.  2.  1.3 4.  5. ]


dtype('float64')

In [ ]:
arr=np.array([1,2,1.3,4,5],dtype=np.int64)
print(arr.dtype)
arr



int64


array([1, 2, 1, 4, 5])

arr=np.array([1,2,3])
arr.dtype
new_arr=arr.astype(np.float64)
new_arr

In [ ]:
#type Casting Error
arr=np.array['1','2','3','hello']#Cannot convert string into int
arr2=arr.astype(np.int64)
arr2

TypeError: 'builtin_function_or_method' object is not subscriptable

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
arr
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.itemsize

8

In [ ]:
###Array Reshaping ->Reshape , Ravel,Flatten#####

#Reshape
arr=np.array([1,2,3,4,5,6,7,8])
reshaped=arr.reshape(2,4)
print(reshaped)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
reshaped2=reshaped.reshape(4,2)
print(reshaped2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
#Ravel
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
reshaped=arr.reshape(2,4)
print(reshaped)
ravel1=reshaped.ravel()#convert any array into 1D array
ravel1

[[1 2 3 4]
 [5 6 7 8]]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
#flatten used to return 1D array of the array
#####The Differnce between flatten and ravel is only thing that the ravel fun reflects the changes in the original array but flatten does not
flat=reshaped.flatten()
flat


array([1, 2, 3, 4, 5, 6, 7, 8])