In [1]:
#Arthmetic Operation
#Addition
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [3]:
#Subtraction
print(a-b)
print(b-a)

[-3 -3 -3]
[3 3 3]


In [7]:
#Division
print(a/b)
print(b//a)

[0.25 0.4  0.5 ]
[4 2 2]


In [5]:
#Multiply
print

[ 4 10 18]


#Remainder(Modulus)
print(a%b)
print(b%a)

In [11]:
#Exponent->Power
print(a**2)
print(b**2)

[1 4 9]
[16 25 36]


In [12]:
#Universal Functions(Ufuncs)
arr=np.array([1,4,9,16])
np.sqrt(arr)

array([1., 2., 3., 4.])

In [13]:
np.exp(arr)#Exponential

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])

In [14]:
#Sin
angles=np.array([0,np.pi,np.pi/2])
print(np.sin(angles))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [5]:
#indexing and Slicing
a=[1,2,3,4,5]
a[-1:-4]#[start index,end index]
a[-1:-4:-1]#also need to include the step value

[5, 4, 3]

In [6]:
a[: :2]#whole array will be printed by the gap of 2

[1, 3, 5]

In [12]:
import numpy as np
arr=np.array([10,20,30,40,50])
#index 0,2,4
arr[::2]

array([10, 30, 50])

In [14]:
#Negative Indexing
print(arr[-1])

50


In [25]:
#Multi-Dimensional Slicing
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0:2,0:3])
print(matrix[1:3,1:3]) #or
print(matrix[1: , 1: ])

[[1 2 3]
 [4 5 6]]
[[5 6]
 [8 9]]
[[5 6]
 [8 9]]


In [26]:
#Index Array (Advanced Indexing)
#np.take -> built in fun to perform indexing and slicing
ind=[0,2]
print(np.take(arr,ind))

[10 30]


In [27]:
#Iterating with nditer
arr=np.array([1,2,3,4,5,6])
for x in np.nditer(arr):
  print(x,end=" ")

1 2 3 4 5 6 

In [29]:
#ndenumerate()-> both index and value is fetched
for ind,x in np.ndenumerate(matrix):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [31]:
#Views vs Copies
arr=np.array([1,2,3,4,5,6,7,8])
view=arr[1:3]
view

array([2, 3])

In [37]:
arr
view[0]=200#update vavlue in view
view
arr#Array gets updated too

array([  1, 200,   3,   4,   5,   6,   7,   8])

In [42]:
#copy
copy=arr[1:3].copy()
copy
copy[0]=2
copy
arr

array([  1, 200,   3,   4,   5,   6,   7,   8])

In [2]:
#Transpose Martix
import numpy as np
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [3]:
print (arr.transpose())

[[1 3]
 [2 4]]


In [6]:
#Swapaxes ->swaps 2 specific axes in a matrix
arr=np.array([[[1,2],[3,4]]])
arr.shape
arr

array([[[1, 2],
        [3, 4]]])

In [9]:
swap=np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

In [10]:
#Concatenation
a=np.array([1,2])
b=np.array([3,4])

In [11]:
combine=np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [15]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
print(np.vstack((a1,a2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
print(np.hstack((a1,a2)))

[[1 2 5 6]
 [3 4 7 8]]


In [19]:
print(np.stack((a1,a2),axis=0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
print(np.stack((a1,a2),axis=1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [27]:
#Spliting Array
a1=np.array([[1,2],[3,4],[7,8],[9,10]])
print(np.split(a1,4))

[array([[1, 2]]), array([[3, 4]]), array([[7, 8]]), array([[ 9, 10]])]


In [30]:
#Repeating
a1=np.array([[1,2],[3,4]])
print(np.repeat(a1,2))

[1 1 2 2 3 3 4 4]


In [33]:
#Tile
a1=np.array([1,2])
print(np.tile(a1,2))

[1 2 1 2]
