In [ ]:
#Aggregate Functions
import numpy as np
arr=np.array([1,2,3,4,5])
print(np.sum(arr))

15


In [ ]:
np.mean(arr)

np.float64(3.0)

In [ ]:
np.median(arr)

np.float64(3.0)

In [ ]:
np.std(arr)

np.float64(1.4142135623730951)

In [ ]:
np.var(arr)

np.float64(2.0)

In [ ]:
np.min(arr)

np.int64(1)

In [ ]:
np.max(arr)

np.int64(5)

In [ ]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix


In [ ]:
print(np.sum(matrix,axis=1))

[ 6 15 24]


In [ ]:
print(np.sum(matrix,axis=0))

[12 15 18]


In [ ]:
#Cumulative Operation->running total
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(np.cumsum(arr))#sum of arr[0],arr[0]+arr[1],arr[0]+arr[1]+arr[2]

[ 1  3  6 10 15]


In [ ]:
print(np.cumprod(arr))#product

[  1   2   6  24 120]


In [ ]:
#Coditional BAsed CHoices
#where
arr

array([1, 2, 3, 4, 5])

In [ ]:
res=np.where(arr<2,"low","high")
res

array(['low', 'high', 'high', 'high', 'high'], dtype='<U4')

In [ ]:
print(np.argwhere(arr<20))

[[0]
 [1]
 [2]
 [3]
 [4]]


In [ ]:
mask=np.logical_and(arr>15,arr<35)
arr[mask]

array([], dtype=int64)

In [ ]:
sk=np.logical_or(arr<4,arr<5)
arr[mask]

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.argwhere(matrix>5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [3]:
#Broadcasting
import numpy as np
image=np.array([[200,150],[100,250]])
image

array([[200, 150],
       [100, 250]])

In [4]:
brightness=image+50
brightness

array([[250, 200],
       [150, 300]])

In [8]:
#Vectorization
#np.vectorize() ->convert the regular function to be appli0ed on array
arr=np.array([1,2,3,4,5])
def square(x):
  return x*x
vfunc=np.vectorize(square)

In [9]:
print(vfunc(arr))

[ 1  4  9 16 25]


In [10]:
#Dealing with missing values
#np.nan->not a number
a=np.array([1,2,np.nan,4])
a

array([ 1.,  2., nan,  4.])

In [13]:
#np.inf and -np.inf ->positive and negative infinites
#np.isnan ->used to detect null values
#np.isinf -> used to detect infinite values
#np.isinfinite ->used to detect finite values
print(np.isnan(a))
b=np.array([1,np.nan,np.inf,10.2,40])
print(np.isinf(b))

[False False  True False]
[False False  True False False]


In [15]:
new_b=np.nan_to_num(b)
print(new_b)

[1.00000000e+000 0.00000000e+000 1.79769313e+308 1.02000000e+001
 4.00000000e+001]
